POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json

{
  "name": "Other product",
  "price": 200
}

###

GET http://localhost:8000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIyNjI5OTMsInN1YiI6Ijk3MDk1ZTQ2LTJlYmQtNDU3NC1iYmFjLTYxMWE5ZTA3YzM4ZSJ9.C3df1gzSBv9YQg8USsqkEySC8snfZXZqfRLs47T5pM8

###

GET http://localhost:8000/products/190c0602-1737-4902-a42d-522ce1921f8f HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/products/190c0602-1737-4902-a42d-522ce1921f8f HTTP/1.1
Content-Type: application/json

{
  "name": "My product Update",
  "price": 200
}

###

DELETE http://localhost:8000/products/190c0602-1737-4902-a42d-522ce1921f8f HTTP/1.1
Content-Type: application/json

